version: '3.8'
 
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"  # Porta padrão do Uptime Kuma
    volumes:
      - uptime-kuma-data:/app/data
    environment:
      - TZ=America/Sao_Paulo  # Ajuste seu fuso horário
 
volumes:
  uptime-kuma-data:
    name: uptime-kuma-data